//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SLC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM SnowInventory.inv.DbVersionHistory.
        /// </summary>
        internal static string DUJDbVersionHistory {
            get {
                return ResourceManager.GetString("DUJDbVersionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM msdb.dbo.sysjobhistory where sql_severity &gt; 0 order by run_date desc, run_time desc.
        /// </summary>
        internal static string DUJsysjobhistory {
            get {
                return ResourceManager.GetString("DUJsysjobhistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM SnowLicenseManager.dbo.tblCIDDataSource.
        /// </summary>
        internal static string DUJtblCIDDataSource {
            get {
                return ResourceManager.GetString("DUJtblCIDDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM SnowLicenseManager.dbo.tblErrorLog.
        /// </summary>
        internal static string DUJtblErrorLog {
            get {
                return ResourceManager.GetString("DUJtblErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM SnowLicenseManager.dbo.tblInventoryDatabaseLog.
        /// </summary>
        internal static string DUJtblInventoryDatabaseLog {
            get {
                return ResourceManager.GetString("DUJtblInventoryDatabaseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM SnowLicenseManager.dbo.tblJobLog.
        /// </summary>
        internal static string DUJtblJobLog {
            get {
                return ResourceManager.GetString("DUJtblJobLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM SnowLicenseManager.dbo.tblJobLogHistory.
        /// </summary>
        internal static string DUJtblJobLogHistory {
            get {
                return ResourceManager.GetString("DUJtblJobLogHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM SnowLicenseManager.dbo.tblJobLogMetrics.
        /// </summary>
        internal static string DUJtblJobLogMetrics {
            get {
                return ResourceManager.GetString("DUJtblJobLogMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM SnowLicenseManager.inv.tblJobParallelStep.
        /// </summary>
        internal static string DUJtblJobParallelStep {
            get {
                return ResourceManager.GetString("DUJtblJobParallelStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap slc_logo1 {
            get {
                object obj = ResourceManager.GetObject("slc-logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
